version: '3.3'

services:
  adapter:
    image: 127.0.0.1:5001/opcua-adapter
    build: opcua-adapter/
    environment:
      # OPC-UA config is set in the source code
      # Panta Rhei configuration
      CLIENT_NAME: "mqtt-adapter"
      SYSTEM_NAME: "test-topic"
      # "at.srfg.iot.dtz"
      SENSORTHINGS_HOST: "192.168.48.71:8082"
      BOOTSTRAP_SERVERS: "192.168.48.71:9092,192.168.48.72:9092,192.168.48.73:9092,192.168.48.74:9092,192.168.48.75:9092"
    ports:
      - "9092:9092"
#    networks:
#      - opcua-adapter
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
          memory: 1G
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

### Network
#networks:
#  opcua-adapter:
